/**
 * Zesty.io AutoGenerated Header Component
 * This file is used in [...slug.js] for example. It is not necceary and may be deleted or modified as needed.
 *
 */

function Header() {
  return (
    <>
      <header className="theme-main-menu sticky-menu theme-menu-eleven white-vr">
        <div className="inner-content position-relative">
          <div className="d-flex align-items-center justify-content-between">
            <div className="logo order-lg-0">
              <a href="index.html" className="d-block">
                <img src="images/logo/logo_05.png" alt="" width="95" />
              </a>
            </div>

            <div className="right-widget d-flex align-items-center ms-auto ms-lg-0 order-lg-3">
              <a
                href="signin.html"
                className="login-btn-two fw-500 d-flex align-items-center me-3 me-xl-5"
              >
                <img src="images/icon/icon_20.svg" alt="" className="me-2" />
                <span>login</span>
              </a>
              <a
                href="contact-us.html"
                className="start-btn-two fw-500 position-relative d-none d-lg-block"
              >
                Get Started
              </a>
            </div>

            <nav className="navbar navbar-expand-lg order-lg-2">
              <button
                className="navbar-toggler d-block d-lg-none"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarNav">
                <ul className="navbar-nav">
                  <li className="d-block d-lg-none">
                    <div className="logo">
                      <a href="index.html" className="d-block">
                        <img src="images/logo/logo_05.png" alt="" width="95" />
                      </a>
                    </div>
                  </li>
                  <li className="nav-item active dropdown mega-dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      role="button"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      aria-expanded="false"
                    >
                      Home
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <div className="row justify-content-center gx-2">
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_01.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>insurance</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-2.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_02.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Sass Product</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-3.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_03.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>App Landing</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-4.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_04.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Personal Portfolio</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-5.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_05.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>N.P. Charity</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-6.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_06.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>SEO & Digital Agency</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-7.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_07.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Web Hosting</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-8.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_08.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Crypto</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-9.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_09.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Lead Generation</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-10.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_10.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Agency Modern</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-11.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_11.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Design Agency</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-12.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_12.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Education</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <a
                              href="index-13.html"
                              className="d-block dropdown-item text-center"
                            >
                              <span className="img-meta">
                                <img
                                  src="images/menu/home_13.jpg"
                                  alt=""
                                  className="w-100"
                                />
                              </span>
                              <span>Real Estate</span>
                            </a>
                          </div>
                          <div className="col-lg-2 mt-15">
                            <span className="img-meta">
                              <img
                                src="images/menu/home_cs.jpg"
                                alt=""
                                className="w-100"
                              />
                            </span>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </li>
                  <li className="nav-item dropdown mega-dropdown-md">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      role="button"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      aria-expanded="false"
                    >
                      Pages
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <div className="row">
                          <div className="col-lg-4">
                            <div className="menu-column">
                              <h6 className="mega-menu-title">Essential</h6>
                              <ul className="style-none mega-dropdown-list">
                                <li>
                                  <a
                                    href="about-v1.html"
                                    className="dropdown-item"
                                  >
                                    <span>About- insurance</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="about-v2.html"
                                    className="dropdown-item"
                                  >
                                    <span>About- Real Estate</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="about-v3.html"
                                    className="dropdown-item"
                                  >
                                    <span>About- Agency</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="about-v4.html"
                                    className="dropdown-item"
                                  >
                                    <span>About- L.Generation</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="pricing.html"
                                    className="dropdown-item"
                                  >
                                    <span>Pricing</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="pricing-v2.html"
                                    className="dropdown-item"
                                  >
                                    <span>Pricing- Sass Product</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="pricing-v3.html"
                                    className="dropdown-item"
                                  >
                                    <span>Pricing- Web Hosting</span>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                          <div className="col-lg-4">
                            <div className="menu-column">
                              <h6 className="mega-menu-title">Features</h6>
                              <ul className="style-none mega-dropdown-list">
                                <li>
                                  <a
                                    href="feature(sass).html"
                                    className="dropdown-item"
                                  >
                                    <span>Feature- Sass Product</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="feature(web-hosting).html"
                                    className="dropdown-item"
                                  >
                                    <span>Feature- Web Hosting</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="service-v1.html"
                                    className="dropdown-item"
                                  >
                                    <span>Service- insurance</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="service-v2.html"
                                    className="dropdown-item"
                                  >
                                    <span>Service- Real Estate</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="service-v3.html"
                                    className="dropdown-item"
                                  >
                                    <span>Service- L.Generation</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="service-v4.html"
                                    className="dropdown-item"
                                  >
                                    <span>Service- Agency</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="service-details.html"
                                    className="dropdown-item"
                                  >
                                    <span>Service Details</span>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                          <div className="col-lg-4">
                            <div className="menu-column">
                              <h6 className="mega-menu-title">Others</h6>
                              <ul className="style-none mega-dropdown-list">
                                <li>
                                  <a
                                    href="testimonial.html"
                                    className="dropdown-item"
                                  >
                                    <span>Testimonials</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="team-v1.html"
                                    className="dropdown-item"
                                  >
                                    <span>Team One</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="team-v2.html"
                                    className="dropdown-item"
                                  >
                                    <span>Team Two</span>
                                  </a>
                                </li>
                                <li>
                                  <a href="faq.html" className="dropdown-item">
                                    <span>FAQ</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="signin.html"
                                    className="dropdown-item"
                                  >
                                    <span>Signin</span>
                                  </a>
                                </li>
                                <li>
                                  <a
                                    href="signup.html"
                                    className="dropdown-item"
                                  >
                                    <span>Signup</span>
                                  </a>
                                </li>
                                <li>
                                  <a href="404.html" className="dropdown-item">
                                    <span>404 Error</span>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </li>
                  <li className="nav-item dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      role="button"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      aria-expanded="false"
                    >
                      Portfolio
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <a href="portfolio-v1.html" className="dropdown-item">
                          <span>Portfolio 01</span>
                        </a>
                      </li>
                      <li>
                        <a href="portfolio-v2.html" className="dropdown-item">
                          <span>Portfolio 02</span>
                        </a>
                      </li>
                      <li>
                        <a href="portfolio-v3.html" className="dropdown-item">
                          <span>Portfolio 03</span>
                        </a>
                      </li>
                      <li>
                        <a href="portfolio-v4.html" className="dropdown-item">
                          <span>Portfolio 04</span>
                        </a>
                      </li>
                      <li>
                        <a href="portfolio-v5.html" className="dropdown-item">
                          <span>Portfolio 05</span>
                        </a>
                      </li>
                      <li>
                        <a href="portfolio-v6.html" className="dropdown-item">
                          <span>Portfolio 06</span>
                        </a>
                      </li>
                      <li>
                        <a href="portfolio-v7.html" className="dropdown-item">
                          <span>Portfolio 07</span>
                        </a>
                      </li>
                      <li className="dropdown-submenu dropdown">
                        <a
                          className="dropdown-item dropdown-toggle"
                          data-bs-toggle="dropdown"
                          data-bs-auto-close="outside"
                          aria-expanded="false"
                          href="#"
                        >
                          <span>Single Portfolio</span>
                        </a>
                        <ul className="dropdown-menu">
                          <li>
                            <a
                              href="portfolio-details-v1.html"
                              className="dropdown-item"
                            >
                              <span>Portfolio details One</span>
                            </a>
                          </li>
                          <li>
                            <a
                              href="portfolio-details-v2.html"
                              className="dropdown-item"
                            >
                              <span>Portfolio details Two</span>
                            </a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li className="nav-item dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      role="button"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      aria-expanded="false"
                    >
                      Blog
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <a href="blog-v1.html" className="dropdown-item">
                          <span>List With sidebar</span>
                        </a>
                      </li>
                      <li>
                        <a href="blog-v2.html" className="dropdown-item">
                          <span>Grid With sidebar</span>
                        </a>
                      </li>
                      <li>
                        <a href="blog-v3.html" className="dropdown-item">
                          <span>Grid Layout</span>
                        </a>
                      </li>
                      <li>
                        <a href="blog-details.html" className="dropdown-item">
                          <span>Blog Details</span>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li className="nav-item dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      role="button"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      aria-expanded="false"
                    >
                      Contact
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <a href="contact-us.html" className="dropdown-item">
                          <span>Contact- insurance</span>
                        </a>
                      </li>
                      <li>
                        <a href="contact-us-v2.html" className="dropdown-item">
                          <span>Contact- Agency</span>
                        </a>
                      </li>
                      <li>
                        <a href="contact-us-v3.html" className="dropdown-item">
                          <span>Contact- Web Hosting</span>
                        </a>
                      </li>
                      <li>
                        <a href="contact-us-v4.html" className="dropdown-item">
                          <span>Contact- L.Generation</span>
                        </a>
                      </li>
                    </ul>
                  </li>
                </ul>

                <div className="mobile-content d-block d-lg-none">
                  <div className="d-flex flex-column align-items-center justify-content-center mt-70">
                    <a
                      href="contact-us.html"
                      className="start-btn-two fw-500 position-relative"
                    >
                      Get Started
                    </a>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </header>
    </>
  );
}

export default Header;
