// generated by lib/sync.js
 // This is a required an autogenerated file from the Zesty.io NextJS integration
 // This file is overwritten everytime the integration script is run
     
 import Clipping from './Clipping';
import Widget from './Widget';
import Homepage from './Homepage';
import SimplePage from './SimplePage';
import SidebarContactForm from './SidebarContactForm';
import Blog from './Blog';
import Article from './Article';
import HomepageTile from './HomepageTile';
import Category from './Category';
import Author from './Author';
import Tag from './Tag';
import CtaCard from './CtaCard';
import SignUpStep from './SignUpStep';
import ValueProp from './ValueProp';
import CompanyStatistic from './CompanyStatistic';
import ServicesPage from './ServicesPage';
import Testimonial from './Testimonial';
import Faq from './Faq';
import SocialMedia from './SocialMedia';
import ServicesCard from './ServicesCard';
import ContactPage from './ContactPage';
import NavBarItem from './NavBarItem';
import NavBar from './NavBar';
import Footer from './Footer';
import Icon from './Icon';
 
 export {
   Clipping, Widget, Homepage, SimplePage, SidebarContactForm, Blog, Article, HomepageTile, Category, Author, Tag, CtaCard, SignUpStep, ValueProp, CompanyStatistic, ServicesPage, Testimonial, Faq, SocialMedia, ServicesCard, ContactPage, NavBarItem, NavBar, Footer, Icon
 }